// <auto-generated />
using CookBook.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CookBook.Migrations
{
    [DbContext(typeof(CookBookContext))]
    [Migration("20260512202642_DictEntities")]
    partial class DictEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CookBook.Models.Allergen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Allergens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Gluten"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Orzechy"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mleko"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Jaja"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Ryby"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Skorupiaki"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Pomidory"
                        });
                });

            modelBuilder.Entity("CookBook.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Zupa"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Danie główne"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Deser"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Śniadanie"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Obiad"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Kolacja"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Przekąska"
                        });
                });

            modelBuilder.Entity("CookBook.Models.DifficultyLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DifficultyLevels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Łatwy"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Średni"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Trudny"
                        });
                });

            modelBuilder.Entity("CookBook.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Wegetariańskie"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Wegańskie"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bezglutenowe"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Dla dzieci"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Szybkie"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Na imprezę"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Słodkie"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Słone"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Ostre"
                        });
                });

            modelBuilder.Entity("CookBook.Models.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "gram"
                        },
                        new
                        {
                            Id = 2,
                            Name = "mililitr"
                        },
                        new
                        {
                            Id = 3,
                            Name = "sztuka"
                        },
                        new
                        {
                            Id = 4,
                            Name = "szklanka"
                        },
                        new
                        {
                            Id = 5,
                            Name = "łyżeczka"
                        },
                        new
                        {
                            Id = 6,
                            Name = "łyżka"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
