// <auto-generated />
using System;
using CookBook.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CookBook.Migrations
{
    [DbContext(typeof(CookBookContext))]
    [Migration("20260512203654_Ingredients")]
    partial class Ingredients
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CookBook.Models.Allergen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Allergens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Gluten"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Orzechy"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mleko"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Jaja"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Ryby"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Skorupiaki"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Pomidory"
                        });
                });

            modelBuilder.Entity("CookBook.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Zupa"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Danie główne"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Deser"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Śniadanie"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Obiad"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Kolacja"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Przekąska"
                        });
                });

            modelBuilder.Entity("CookBook.Models.DifficultyLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DifficultyLevels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Łatwy"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Średni"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Trudny"
                        });
                });

            modelBuilder.Entity("CookBook.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("DensityGramsPerMl")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UnitId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("CookBook.Models.IngredientAllergen", b =>
                {
                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<int>("AllergenId")
                        .HasColumnType("int");

                    b.HasKey("IngredientId", "AllergenId");

                    b.HasIndex("AllergenId");

                    b.ToTable("IngredientAllergens");
                });

            modelBuilder.Entity("CookBook.Models.IngredientNutrition", b =>
                {
                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<int>("NutritionTypeId")
                        .HasColumnType("int");

                    b.Property<double>("AmountPer100g")
                        .HasColumnType("float");

                    b.HasKey("IngredientId", "NutritionTypeId");

                    b.HasIndex("NutritionTypeId");

                    b.ToTable("IngredientNutritions");
                });

            modelBuilder.Entity("CookBook.Models.NutritionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("NutritionTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Kalorie"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Białko"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tłuszcze"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Węglowodany"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Błonnik"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Cukry"
                        });
                });

            modelBuilder.Entity("CookBook.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Wegetariańskie"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Wegańskie"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bezglutenowe"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Dla dzieci"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Szybkie"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Na imprezę"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Słodkie"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Słone"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Ostre"
                        });
                });

            modelBuilder.Entity("CookBook.Models.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "gram"
                        },
                        new
                        {
                            Id = 2,
                            Name = "mililitr"
                        },
                        new
                        {
                            Id = 3,
                            Name = "sztuka"
                        },
                        new
                        {
                            Id = 4,
                            Name = "szklanka"
                        },
                        new
                        {
                            Id = 5,
                            Name = "łyżeczka"
                        },
                        new
                        {
                            Id = 6,
                            Name = "łyżka"
                        });
                });

            modelBuilder.Entity("CookBook.Models.Ingredient", b =>
                {
                    b.HasOne("CookBook.Models.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("CookBook.Models.IngredientAllergen", b =>
                {
                    b.HasOne("CookBook.Models.Allergen", "Allergen")
                        .WithMany()
                        .HasForeignKey("AllergenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CookBook.Models.Ingredient", "Ingredient")
                        .WithMany("IngredientAllergens")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allergen");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("CookBook.Models.IngredientNutrition", b =>
                {
                    b.HasOne("CookBook.Models.Ingredient", "Ingredient")
                        .WithMany("IngredientNutritions")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CookBook.Models.NutritionType", "NutritionType")
                        .WithMany()
                        .HasForeignKey("NutritionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("NutritionType");
                });

            modelBuilder.Entity("CookBook.Models.Ingredient", b =>
                {
                    b.Navigation("IngredientAllergens");

                    b.Navigation("IngredientNutritions");
                });
#pragma warning restore 612, 618
        }
    }
}
